version: "3.1"

services:
  www:
    container_name: www
    build: .

    volumes:
      -  .:/var/www
    links:
      - db
    ports:
      - 8000:80
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=barjuan
      - MYSQL_USER=daw
      - MYSQL_PASSWORD=test
    volumes:
      - ./dump:/docker.entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db:db
    ports:
      - 8001:80
    environment:
      - MYSQL_USER=root 
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test

volumes:
    persistent: